#!/usr/bin/env python
import logging.config
import threading
import time
from flask import Flask
from remote_host_file_sync_service import get_conf_path
from remote_host_file_sync_service import config
from remote_host_file_sync_service.api.restplus import api
from remote_host_file_sync_service.api import mongo_data


app = Flask(__name__)
logging.config.fileConfig(get_conf_path('logging.conf'), disable_existing_loggers=False)
log = logging.getLogger(__name__)



def configure_app(ecs_app):
    ecs_app.config['SERVER_NAME'] = config.FLASK_SERVER_NAME
    ecs_app.config['SWAGGER_UI_DOC_EXPANSION'] = config.RESTPLUS_SWAGGER_UI_DOC_EXPANSION
    ecs_app.config['RESTPLUS_VALIDATE'] = config.RESTPLUS_VALIDATE
    ecs_app.config['RESTPLUS_MASK_SWAGGER'] = config.RESTPLUS_MASK_SWAGGER
    ecs_app.config['ERROR_404_HELP'] = config.RESTPLUS_ERROR_404_HELP


def initialize_app(ecs_app):
    configure_app(ecs_app)
    api.init_app(ecs_app)
    mongo_data.init_app(ecs_app)


def main():
    initialize_app(app)
    log.info('>>>>> Starting development server at http://{}/ <<<<<'.format(app.config['SERVER_NAME']))
    app.run(debug=config.FLASK_DEBUG)

if __name__ == "__main__":
    main()

